schema_version = "1.0.0"

# TOML template from https://docs.blender.org/manual/en/4.2/extensions/getting_started.html
id = "bonejuice"
version = "0.1.1"
name = "BoneJuice"
tagline = "Armature utility plugin for Blender"
maintainer = "Alan O'Cull <alanocull.com>"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional: add-ons can list which resources they will require:
# * "files" (for access of any filesystem operations)
# * "network" (for internet access)
# * "clipboard" (to read and/or write the system clipboard)
# * "camera" (to capture photos and videos)
# * "microphone" (to capture audio)
# permissions = ["files", "network"]

website = "https://github.com/arocull/BoneJuice"

# https://docs.blender.org/manual/en/4.2/extensions/tags.html
tags = ["Rigging"]

blender_version_min = "4.2.0"
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/4.2/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2024 Alan O'Cull",
]

# Optional list of supported platforms. If omitted, the extension will be available in all operating systems.
# platforms = ["windows-amd64", "macos-arm64", "linux-x86_64"]
# Other supported platforms: "windows-arm64", "macos-x86_64"

# Optional: bundle 3rd party Python modules.
# https://docs.blender.org/manual/en/4.2/extensions/python_wheels.html
# wheels = [
#   "./wheels/hexdump-3.3-py3-none-any.whl",
#   "./wheels/jsmin-3.0.1-py3-none-any.whl"
# ]

# Optional: build setting.
# https://docs.blender.org/manual/en/4.2/extensions/command_line_arguments.html#command-line-args-extension-build
[build]
paths_exclude_pattern = [
  "/.git/",
  "__pycache__/",
  "/blender_autocomplete/",

  "/tests/",
  "/docs/",
  "/build/",
  
  "*.cmd",
  "Makefile",
]